<div class="bs-docs-selection">
    <div class="well">
<?php

$form->setAttribute('action', $this->url('admin/category', array('action' => 'add')));
$from->prepare();

echo $this->form()->openTag($form);
echo '<fieldset><legend>Category add</legend>';
foreach ($form as $element){
    echo '<div class="form-group">';
    $attributes = $element->getAttributes();
    
    if($element->getLabel()){
        $element->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
        if(isset($attributes['required'])){
            $element->setlabel($element->getLabel() . ' *');
        }
    }
    if(isset($attributes['type']) && $attributes['type'] == 'text')
    {
        echo $this->formLabel($element);
        echo '<div class="col-lg-10">';
        echo $this->formInput($element);
        echo '</div>';
    } elseif(isset($attributes['type']) && $attributes['type'] == 'textarea'){
        echo $this->formlabel($element);
        echo '<div class="col-lg-10">';
    }
}
?>
    </div>
</div>
