<H1>Admin >-> Category</H1>
<a href="/admin/category/add/">Add new Category</a></br></br>

<?php 
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s> 
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"> 
        &times;
        </button>
        <ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');

   echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
   echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
   echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
   echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<TABLE class="table-striped table-hover" width="100%">
    <TBODY>
        <TR>
            <TH>#</TH>
            <TH>Key</TH>
            <TH>Name</TH>
            <TH>Action</TH>
        </TR>

        <?php foreach ( $category as $item ){
            echo "<TR>
                    <td>{$item->getId()}</td>
                    <td>{$item->getCategoryKey()}</td>
                    <td>{$item->getCategoryName()}</td>";
            echo '<td><a href="'. $this->url('admin/category', array('action' => 'edit', 'id' => $item->getId())) . '">Edit</a>&nbsp;&nbsp;
                      <a href="'. $this->url('admin/category', array('action' => 'delete', 'id' => $item->getId())) . '" onclick="if (confirm(\'Delete record?\')) { document.location = this.href; } return false;">Delete</a> </td></TR>';
            }
        ?>
        
    </TBODY>
</TABLE>