<?php

echo "<article>
    <div class='page-header'>
        <h1 style='font-size: 2em;'>{$article->getTitle()}</h1>
    </div>
    <div>
        {$article->getFullArticle()}
    </div>
    </article>";
?>

<div class="bs-docs-section">
    <div class="well">
<?php

$form->setAttribute('action', $this->url('blog', array('action' => 'comment-add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
    echo '<fieldset><legend>Add comment</legend>';
        echo '<div id="comment_errors"></div>';
        
        $e = $form->get('userEmail');
        $e->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
        echo '<div id="form-group">';
        echo $this->formLabel($e);
        echo "<div class='col-lg-10'>{$this->formEmail($e)}</div>";
        echo '<div>';
        
        $e = $form->get('comment');
        $e->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
        echo '<div id="form-group">';
        echo $this->formLabel($e);
        echo "<div class='col-lg-10'>{$this->formTextarea($e)}</div>";
        echo '<div>';
        
        echo "<input type='hidden' value='{$article->getId()}' name='article'>";
        
echo $this->formRow($form->get('submit'));
echo '</fieldset>';
echo $this->form->closeTag();
?>
        
        
    </div>
</div>