<div class="bs-docs-selection">
    <div class="well">
<?php

$form->setAttribute('action', $this->url('admin/comment', array('action' => 'edit', 'id' => $id)));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo '<fieldset><legend>Comment edit</legend>';
foreach ($form as $element){
    echo '<div class="form-group">';
    $attributes = $element->getAttributes();
    
    //genegation label-caption  part
    $label = '';
    if($element->getLabel()){
        $label = $element->getLabel();
        $element->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
        
        if(isset($attributes['required'])){
            $label .= ' *';
        }
        $label = "<label class='col-lg-2 control-label'>{$label}</label>";
    }
    
    //generation form-elements part
    $type = isset($attributes['type']) ? $attributes['type'] : '';
    $formElement = '';
    switch ($type){
        case 'text':
                $formElement = $this->formInput($element);
                break;
        case 'textarea':
                $formElement = $this->formTextArea($element);
                break;
        case 'select':
                $formElement = $this->formSelect($element);
                break;
        default:
                $formElement = $this->formRow($element);
                $label = '';
                break;
    }
    
    //pullout label and current element to screen
    echo "{$label}<div class='col-lg-10'>{$formElement}</div>";
    echo '</div>';
}
echo '</fieldset>';
echo $this->form()->closeTag();
?>
    </div>
</div>

<script src="/js/ckeditor/ckeditor.js"></script>

